# Generated by Django 5.2.2 on 2025-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('is_https', models.BooleanField()),
                ('missing_headers', models.TextField()),
                ('all_headers', models.JSONField()),
            ],
        ),
    ]
